
#include "DriveCommands.h"
#include "../OI.h"
#include "../WPILib/RobotDrive.h"
#include "../RobotMap.h"
#include "../WPILib/DriverStationLCD.h"
#include <stdio.h>

DriveCommand::DriveCommand(): MyRobotBaseCommand() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// The following variables are automatically assigned by
	// robotbuilder and will be updated the next time you export to
	// Java from robot builder. Do not put any code or make any change
	// in the following block or it will be lost on an update. To
	// prevent this subsystem from being automatically updated, delete
	// the following line.
	wpi_assert(Robot::drive != NULL);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	printf("constructed new drive command\n");
	Requires(Robot::drive);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

}

// Called just before this Command runs the first time
void DriveCommand::Initialize() {
}

// Called repeatedly when this Command is scheduled to run
void DriveCommand::Execute() {
    if (isRunning()) {
        return;
    }
    setRunning(true);
    printf("calling auto_drive_straight with distance %f speed %f\n", m_distance, m_speed);
	Robot::drive->auto_drive_straight(m_distance, m_speed);
	printf("drive straight done\n");
    setFinished(true);
}

// Called once after isFinished returns true
void DriveCommand::End() {
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DriveCommand::Interrupted() {
	printf("Command Interupted !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n");
	End();
}

TurnCommand::TurnCommand() : MyRobotBaseCommand() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// The following variables are automatically assigned by
	// robotbuilder and will be updated the next time you export to
	// Java from robot builder. Do not put any code or make any change
	// in the following block or it will be lost on an update. To
	// prevent this subsystem from being automatically updated, delete
	// the following line.
	wpi_assert(Robot::drive != NULL);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drive);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

}

// Called just before this Command runs the first time
void TurnCommand::Initialize() {
}

// Called repeatedly when this Command is scheduled to run
void TurnCommand::Execute() {
        if (isRunning()) {
            return;
        }
        setRunning(true);
        if (m_angle < 0) {
        	printf("turning left radius %f angle %f speed %f\n", m_radius, -m_angle, m_speed);
            Robot::drive->auto_turn_left(m_radius, -m_angle, m_speed);
        }
        else {
        	printf("turning right radius %f angle %f speed %f\n", m_radius, m_angle, m_speed);
            Robot::drive->auto_turn_right(m_radius, m_angle, m_speed);
        }
        printf("turn command done\n");
        setFinished(true);
}

// Called once after isFinished returns true
void TurnCommand::End() {
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void TurnCommand::Interrupted() {
	printf("Command Interupted !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n");
	End();
}
